global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.10.20:6969']

  - job_name: 'mysql'
    static_configs:
      - targets: ['192.168.10.30:9104']
